### ISSUE TITLE
简化的 URL

### ISSUE THREAD

**Issue by junyilou** [sinchang/cn-starbucks-stores-data#664]
作者您好，在研究 API 时偶然发现，URL 后方的参数其实是不必要的

> https://www.starbucks.com.cn/api/stores/nearby?lat=31.231706&lon=121.472644&limit=1000&locale=ZH&features=&radius=10000000000

可以改为

> https://www.starbucks.com.cn/api/stores

这将直接包含中国全部门店，不会按照后面提供的经纬度进行排序，与设置了 radius 为 10000000000 的结果相同

如果您对星巴克中国网站的 API 有其他有意思的发现，还请多多分享！

**Comment by sinchang** [comment]
@junyilou 谢谢 ：）
